# Generated by Django 5.2.8 on 2026-01-22 03:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_remove_course_instructor_course_instructors_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubeCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Identifier for this credential set (e.g., 'main_channel')", max_length=100, unique=True)),
                ('channel_id', models.CharField(blank=True, help_text='YouTube channel ID', max_length=50, null=True)),
                ('channel_title', models.CharField(blank=True, help_text='YouTube channel name', max_length=255, null=True)),
                ('access_token', models.TextField(help_text='OAuth access token (encrypted)')),
                ('refresh_token', models.TextField(help_text='OAuth refresh token (encrypted)')),
                ('token_expiry', models.DateTimeField(blank=True, help_text='When the access token expires', null=True)),
                ('daily_quota_used', models.IntegerField(default=0, help_text='API quota units used today')),
                ('quota_reset_date', models.DateField(blank=True, help_text='Date when quota was last reset', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this credential is active for uploads')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'YouTube Credential',
                'verbose_name_plural': 'YouTube Credentials',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('s3_key', models.CharField(blank=True, help_text='Object storage key (path) for the video file', max_length=500, null=True)),
                ('s3_bucket', models.CharField(blank=True, help_text='S3 bucket name', max_length=100, null=True)),
                ('original_filename', models.CharField(blank=True, help_text='Original filename from upload', max_length=255, null=True)),
                ('file_size', models.BigIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('content_type', models.CharField(default='video/mp4', help_text='MIME type of the video', max_length=100)),
                ('youtube_video_id', models.CharField(blank=True, help_text='YouTube video ID after successful upload', max_length=50, null=True, unique=True)),
                ('youtube_url', models.URLField(blank=True, help_text='Full YouTube URL for embedding', null=True)),
                ('youtube_privacy', models.CharField(choices=[('private', 'Private'), ('unlisted', 'Unlisted'), ('public', 'Public')], default='unlisted', help_text='YouTube video privacy status', max_length=20)),
                ('youtube_upload_progress', models.IntegerField(default=0, help_text='Upload progress percentage (0-100)')),
                ('status', models.CharField(choices=[('pending', 'Pending Upload'), ('uploading_s3', 'Uploading to Storage'), ('s3_complete', 'Storage Upload Complete'), ('queued', 'Queued for YouTube Upload'), ('uploading_youtube', 'Uploading to YouTube'), ('processing', 'YouTube Processing'), ('ready', 'Ready'), ('failed', 'Failed')], db_index=True, default='pending', max_length=30)),
                ('error_message', models.TextField(blank=True, help_text='Error details if upload failed', null=True)),
                ('retry_count', models.IntegerField(default=0, help_text='Number of upload retry attempts')),
                ('celery_task_id', models.CharField(blank=True, help_text='Celery task ID for tracking', max_length=100, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, help_text='Video duration in seconds', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('s3_uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('youtube_uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('course_content', models.OneToOneField(blank=True, help_text='Associated course content (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video', to='courses.coursecontent')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_videos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='videos_vide_status_e696e3_idx'), models.Index(fields=['uploaded_by', 'status'], name='videos_vide_uploade_92e84a_idx')],
            },
        ),
    ]
