# Generated by Django 5.2.8 on 2026-01-08 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_remove_course_instructor_course_instructors_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('ONE_TIME', 'One-time'), ('SUBSCRIPTION', 'Subscription')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='BDT', max_length=10)),
                ('tran_id', models.CharField(max_length=64, unique=True)),
                ('sessionkey', models.CharField(blank=True, max_length=128, null=True)),
                ('gateway_page_url', models.URLField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('INVALID', 'Invalid'), ('REFUNDED', 'Refunded')], default='INITIATED', max_length=20)),
                ('val_id', models.CharField(blank=True, max_length=128, null=True)),
                ('bank_tran_id', models.CharField(blank=True, max_length=128, null=True)),
                ('card_type', models.CharField(blank=True, max_length=64, null=True)),
                ('store_amount', models.CharField(blank=True, max_length=32, null=True)),
                ('verify_sign', models.CharField(blank=True, max_length=128, null=True)),
                ('verify_sign_sha2', models.CharField(blank=True, max_length=256, null=True)),
                ('risk_level', models.CharField(blank=True, max_length=32, null=True)),
                ('risk_title', models.CharField(blank=True, max_length=64, null=True)),
                ('init_response', models.JSONField(blank=True, null=True)),
                ('callback_payload', models.JSONField(blank=True, null=True)),
                ('validation_response', models.JSONField(blank=True, null=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, help_text='Course being purchased (optional for subscription payments)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_transactions', to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
