# Generated by Django 5.2.8 on 2026-01-08 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # ('enrollments', '0001_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='paymenttransaction',
        #     name='enrollment',
        #     field=models.ForeignKey(blank=True, help_text='Enrollment created after successful payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='enrollments.enrollment'),
        # ),
    ]

