# Generated by Django 5.2.8 on 2026-02-20 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_paymenttransaction_enrollment'),
        ('prints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='print_order',
            field=models.ForeignKey(blank=True, help_text='The print order associated with this payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='prints.printorder'),
        ),
    ]
