# Generated by Django 5.2.8 on 2025-12-18 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MosqueCourseRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mosque_name', models.CharField(max_length=255, verbose_name='Mosque Name')),
                ('full_name_bangla', models.CharField(max_length=255, verbose_name='Full Name (Bangla)')),
                ('full_name_english', models.CharField(max_length=255, verbose_name='Full Name (English)')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('mobile_number', models.CharField(max_length=20, verbose_name='Mobile Number')),
                ('mosque_address', models.TextField(verbose_name='Full Mosque Address')),
                ('upazila', models.CharField(max_length=100, verbose_name='Upazila')),
                ('district', models.CharField(max_length=100, verbose_name='District')),
                ('profession', models.CharField(choices=[('শিক্ষক', 'শিক্ষক'), ('ডাক্তার', 'ডাক্তার'), ('ইঞ্জিনিয়ার', 'ইঞ্জিনিয়ার'), ('আইনজীবী', 'আইনজীবী'), ('কৃষক', 'কৃষক'), ('ব্যবসায়ী', 'ব্যবসায়ী'), ('চাকরিজীবী', 'চাকরিজীবী'), ('ফ্রিল্যান্সার', 'ফ্রিল্যান্সার'), ('ছাত্র', 'ছাত্র'), ('চিকিৎসক', 'চিকিৎসক'), ('অন্যান্য', 'অন্যান্য')], max_length=50, verbose_name='Profession')),
                ('interested_person', models.CharField(choices=[('নিজে আসতে চায়', 'নিজে আসতে চায়'), ('অন্য কাউকে পাঠাতে চায়', 'অন্য কাউকে পাঠাতে চায়')], max_length=50, verbose_name='Interested Person')),
                ('course_source', models.CharField(choices=[('ফেসবুক পোস্টের মাধ্যমে', 'ফেসবুক পোস্টের মাধ্যমে'), ('বক্তব্যের মাধ্যমে', 'বক্তব্যের মাধ্যমে'), ('পরিচিত ব্যক্তির মাধ্যমে', 'পরিচিত ব্যক্তির মাধ্যমে'), ('অন্যান্য', 'অন্যান্য')], max_length=50, verbose_name='How did you learn about this course?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mosque Course Registration',
                'verbose_name_plural': 'Mosque Course Registrations',
                'ordering': ['-created_at'],
            },
        ),
    ]
