# Generated by Django 5.2.8 on 2025-12-18 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuranAndDeenCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name_bangla', models.CharField(max_length=255, verbose_name='Full Name (Bangla)')),
                ('full_name_english', models.CharField(max_length=255, verbose_name='Full Name (English)')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('mobile_number', models.CharField(max_length=20, verbose_name='Mobile Number')),
                ('village_locality', models.CharField(max_length=255, verbose_name='Village/Locality')),
                ('post_office', models.CharField(max_length=255, verbose_name='Post Office')),
                ('upazila', models.CharField(max_length=100, verbose_name='Upazila')),
                ('district', models.CharField(choices=[('কক্সবাজার', 'কক্সবাজার'), ('কুড়িগ্রাম', 'কুড়িগ্রাম'), ('কুষ্টিয়া', 'কুষ্টিয়া'), ('কিশোরগঞ্জ', 'কিশোরগঞ্জ'), ('খাগড়াছড়ি', 'খাগড়াছড়ি'), ('খুলনা', 'খুলনা'), ('গাইবান্ধা', 'গাইবান্ধা'), ('গাজীপুর', 'গাজীপুর'), ('গোপালগঞ্জ', 'গোপালগঞ্জ'), ('চট্টগ্রাম', 'চট্টগ্রাম'), ('চাঁদপুর', 'চাঁদপুর'), ('চাঁপাইনবাবগঞ্জ', 'চাঁপাইনবাবগঞ্জ'), ('চুয়াডাঙ্গা', 'চুয়াডাঙ্গা'), ('ঝালকাঠি', 'ঝালকাঠি'), ('ঝিনাইদহ', 'ঝিনাইদহ'), ('টাঙ্গাইল', 'টাঙ্গাইল'), ('ঠাকুরগাঁও', 'ঠাকুরগাঁও'), ('দিনাজপুর', 'দিনাজপুর'), ('ঢাকা', 'ঢাকা'), ('নওগাঁ', 'নওগাঁ'), ('নাটোর', 'নাটোর'), ('নরসিংদী', 'নরসিংদী'), ('নারায়ণগঞ্জ', 'নারায়ণগঞ্জ'), ('নীলফামারী', 'নীলফামারী'), ('নড়াইল', 'নড়াইল'), ('পাবনা', 'পাবনা'), ('পটুয়াখালী', 'পটুয়াখালী'), ('পিরোজপুর', 'পিরোজপুর'), ('পঞ্চগড়', 'পঞ্চগড়'), ('ফেনী', 'ফেনী'), ('ফরিদপুর', 'ফরিদপুর'), ('বাগেরহাট', 'বাগেরহাট'), ('বরগুনা', 'বরগুনা'), ('বরিশাল', 'বরিশাল'), ('বগুড়া', 'বগুড়া'), ('বান্দরবান', 'বান্দরবান'), ('ব্রাহ্মণবাড়িয়া', 'ব্রাহ্মণবাড়িয়া'), ('ভোলা', 'ভোলা'), ('মাগুরা', 'মাগুরা'), ('মাদারীপুর', 'মাদারীপুর'), ('মানিকগঞ্জ', 'মানিকগঞ্জ'), ('ময়মনসিংহ', 'ময়মনসিংহ'), ('মৌলভীবাজার', 'মৌলভীবাজার'), ('মেহেরপুর', 'মেহেরপুর'), ('মুন্সিগঞ্জ', 'মুন্সিগঞ্জ'), ('যশোর', 'যশোর'), ('জয়পুরহাট', 'জয়পুরহাট'), ('জামালপুর', 'জামালপুর'), ('রাজবাড়ী', 'রাজবাড়ী'), ('রাজশাহী', 'রাজশাহী'), ('রাঙামাটি', 'রাঙামাটি'), ('লালমনিরহাট', 'লালমনিরহাট'), ('লক্ষ্মীপুর', 'লক্ষ্মীপুর'), ('শেরপুর', 'শেরপুর'), ('শরীয়তপুর', 'শরীয়তপুর'), ('সুনামগঞ্জ', 'সুনামগঞ্জ'), ('সিরাজগঞ্জ', 'সিরাজগঞ্জ'), ('সিলেট', 'সিলেট'), ('হবিগঞ্জ', 'হবিগঞ্জ')], max_length=100, verbose_name='District')),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('current_age', models.IntegerField(verbose_name='Current Age')),
                ('course_source', models.CharField(choices=[('ফেসবুক পোস্টের মাধ্যমে', 'ফেসবুক পোস্টের মাধ্যমে'), ('বক্তব্যের মাধ্যমে', 'বক্তব্যের মাধ্যমে'), ('পরিচিত ব্যক্তির মাধ্যমে', 'পরিচিত ব্যক্তির মাধ্যমে'), ('অন্যান্য', 'অন্যান্য')], max_length=50, verbose_name='How did you learn about this course?')),
                ('photo', models.FileField(help_text='Accepted formats: PDF, PNG, JPEG', upload_to='quran_deen_course/photos/', verbose_name='Photo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Quran and Deen Course Registration',
                'verbose_name_plural': 'Quran and Deen Course Registrations',
                'ordering': ['-created_at'],
            },
        ),
    ]
