# Generated by Django 5.2.8 on 2025-12-18 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_qurananddeencourse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qurananddeencourse',
            name='photo',
        ),
    ]
