# Generated by Django 5.2.8 on 2025-12-18 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_remove_qurananddeencourse_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsible_person_name', models.CharField(max_length=255, verbose_name="Responsible Person's Name")),
                ('field_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Field/Ground Name')),
                ('village', models.CharField(blank=True, max_length=255, null=True, verbose_name='Village')),
                ('post_office', models.CharField(blank=True, max_length=255, null=True, verbose_name='Post Office')),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Postal Code')),
                ('upazila', models.CharField(blank=True, max_length=100, null=True, verbose_name='Upazila')),
                ('division', models.CharField(blank=True, max_length=100, null=True, verbose_name='Division')),
                ('reference_person_name', models.CharField(blank=True, max_length=255, null=True, verbose_name="Reference Person's Name")),
                ('responsible_person_number', models.CharField(blank=True, max_length=20, null=True, verbose_name="Responsible Person's Number")),
                ('program_type', models.CharField(blank=True, choices=[('মাদ্রাসা উন্নয়ন', 'মাদ্রাসা উন্নয়ন'), ('মসজিদ উন্নয়ন', 'মসজিদ উন্নয়ন'), ('গোরস্থান উন্নয়ন', 'গোরস্থান উন্নয়ন'), ('ইদগাহ উন্নয়ন', 'ইদগাহ উন্নয়ন'), ('দাওয়াতি কাজে', 'দাওয়াতি কাজে'), ('মক্তব উন্নয়ন', 'মক্তব উন্নয়ন')], max_length=50, null=True, verbose_name='Program Type')),
                ('district', models.CharField(blank=True, choices=[('কক্সবাজার', 'কক্সবাজার'), ('কুড়িগ্রাম', 'কুড়িগ্রাম'), ('কুষ্টিয়া', 'কুষ্টিয়া'), ('কিশোরগঞ্জ', 'কিশোরগঞ্জ'), ('খাগড়াছড়ি', 'খাগড়াছড়ি'), ('খুলনা', 'খুলনা'), ('গাইবান্ধা', 'গাইবান্ধা'), ('গাজীপুর', 'গাজীপুর'), ('গোপালগঞ্জ', 'গোপালগঞ্জ'), ('চট্টগ্রাম', 'চট্টগ্রাম'), ('চাঁদপুর', 'চাঁদপুর'), ('চাঁপাইনবাবগঞ্জ', 'চাঁপাইনবাবগঞ্জ'), ('চুয়াডাঙ্গা', 'চুয়াডাঙ্গা'), ('ঝালকাঠি', 'ঝালকাঠি'), ('ঝিনাইদহ', 'ঝিনাইদহ'), ('টাঙ্গাইল', 'টাঙ্গাইল'), ('ঠাকুরগাঁও', 'ঠাকুরগাঁও'), ('দিনাজপুর', 'দিনাজপুর'), ('ঢাকা', 'ঢাকা'), ('নওগাঁ', 'নওগাঁ'), ('নাটোর', 'নাটোর'), ('নরসিংদী', 'নরসিংদী'), ('নারায়ণগঞ্জ', 'নারায়ণগঞ্জ'), ('নীলফামারী', 'নীলফামারী'), ('নড়াইল', 'নড়াইল'), ('পাবনা', 'পাবনা'), ('পটুয়াখালী', 'পটুয়াখালী'), ('পিরোজপুর', 'পিরোজপুর'), ('পঞ্চগড়', 'পঞ্চগড়'), ('ফেনী', 'ফেনী'), ('ফরিদপুর', 'ফরিদপুর'), ('বাগেরহাট', 'বাগেরহাট'), ('বরগুনা', 'বরগুনা'), ('বরিশাল', 'বরিশাল'), ('বগুড়া', 'বগুড়া'), ('বান্দরবান', 'বান্দরবান'), ('ব্রাহ্মণবাড়িয়া', 'ব্রাহ্মণবাড়িয়া'), ('ভোলা', 'ভোলা'), ('মাগুরা', 'মাগুরা'), ('মাদারীপুর', 'মাদারীপুর'), ('মানিকগঞ্জ', 'মানিকগঞ্জ'), ('ময়মনসিংহ', 'ময়মনসিংহ'), ('মৌলভীবাজার', 'মৌলভীবাজার'), ('মেহেরপুর', 'মেহেরপুর'), ('মুন্সিগঞ্জ', 'মুন্সিগঞ্জ'), ('যশোর', 'যশোর'), ('জয়পুরহাট', 'জয়পুরহাট'), ('জামালপুর', 'জামালপুর'), ('রাজবাড়ী', 'রাজবাড়ী'), ('রাজশাহী', 'রাজশাহী'), ('রাঙামাটি', 'রাঙামাটি'), ('লালমনিরহাট', 'লালমনিরহাট'), ('লক্ষ্মীপুর', 'লক্ষ্মীপুর'), ('শেরপুর', 'শেরপুর'), ('শরীয়তপুর', 'শরীয়তপুর'), ('সুনামগঞ্জ', 'সুনামগঞ্জ'), ('সিরাজগঞ্জ', 'সিরাজগঞ্জ'), ('সিলেট', 'সিলেট'), ('হবিগঞ্জ', 'হবিগঞ্জ')], max_length=100, null=True, verbose_name='District')),
                ('program_probable_date', models.DateField(blank=True, null=True, verbose_name="Program's Probable Date")),
                ('venue_google_location_url', models.URLField(blank=True, help_text='URL of the uploaded Google location file (PDF, PNG, JPEG)', max_length=500, null=True, verbose_name="Venue's Google Location URL")),
                ('program_fund_collection', models.JSONField(blank=True, default=list, help_text='List of selected fund collection sources', verbose_name='Program Fund Collection')),
                ('speakers', models.JSONField(default=list, help_text='List of selected speakers (at least one required)', verbose_name='Speakers')),
                ('program_time', models.CharField(blank=True, choices=[('বাদ যোহর', 'বাদ যোহর'), ('বাদ আসর', 'বাদ আসর'), ('বাদ মাগরিব', 'বাদ মাগরিব'), ('বাদ এশা', 'বাদ এশা'), ('রাত', 'রাত')], max_length=50, null=True, verbose_name='Program Time')),
                ('participated_quran_deen_course', models.CharField(blank=True, choices=[('হ্যাঁ', 'হ্যাঁ'), ('না', 'না')], max_length=10, null=True, verbose_name='Have you participated in Quran and Deen education course?')),
                ('mosque_has_maktab', models.CharField(blank=True, choices=[('হ্যাঁ', 'হ্যাঁ'), ('না', 'না')], max_length=10, null=True, verbose_name='Does the mosque have a Maktab?')),
                ('attend_salafi_conferences', models.CharField(blank=True, choices=[('হ্যাঁ', 'হ্যাঁ'), ('না', 'না')], max_length=10, null=True, verbose_name='Do you attend Salafi conferences?')),
                ('subscriber_al_itisam', models.CharField(blank=True, choices=[('হ্যাঁ', 'হ্যাঁ'), ('না', 'না')], max_length=10, null=True, verbose_name='Are you a subscriber of monthly Al Itisam?')),
                ('affiliated_jamiah_salafiyyah', models.CharField(blank=True, choices=[('হ্যাঁ', 'হ্যাঁ'), ('না', 'না')], max_length=10, null=True, verbose_name="Affiliated with Jami'ah Salafiyyah?")),
                ('participated_3day_madrasa', models.CharField(blank=True, choices=[('হ্যাঁ', 'হ্যাঁ'), ('না', 'না')], max_length=10, null=True, verbose_name='Have you participated in 3-day Madrasa?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Program Registration',
                'verbose_name_plural': 'Program Registrations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='qurananddeencourse',
            name='photo_url',
            field=models.URLField(blank=True, help_text='URL of the uploaded photo', max_length=500, null=True, verbose_name='Photo URL'),
        ),
    ]
