# Generated by Django 5.2.8 on 2025-12-18 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_programregistration_qurananddeencourse_photo_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlItisamRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(max_length=255, verbose_name='Your Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('mobile_number', models.CharField(max_length=20, verbose_name='Mobile Number')),
                ('village_locality_institution', models.CharField(blank=True, max_length=255, null=True, verbose_name='Village/Locality/Institution')),
                ('post', models.CharField(blank=True, max_length=255, null=True, verbose_name='Post')),
                ('upazila', models.CharField(blank=True, max_length=100, null=True, verbose_name='Upazila')),
                ('district', models.CharField(blank=True, choices=[('কক্সবাজার', 'কক্সবাজার'), ('কুড়িগ্রাম', 'কুড়িগ্রাম'), ('কুষ্টিয়া', 'কুষ্টিয়া'), ('কিশোরগঞ্জ', 'কিশোরগঞ্জ'), ('খাগড়াছড়ি', 'খাগড়াছড়ি'), ('খুলনা', 'খুলনা'), ('গাইবান্ধা', 'গাইবান্ধা'), ('গাজীপুর', 'গাজীপুর'), ('গোপালগঞ্জ', 'গোপালগঞ্জ'), ('চট্টগ্রাম', 'চট্টগ্রাম'), ('চাঁদপুর', 'চাঁদপুর'), ('চাঁপাইনবাবগঞ্জ', 'চাঁপাইনবাবগঞ্জ'), ('চুয়াডাঙ্গা', 'চুয়াডাঙ্গা'), ('ঝালকাঠি', 'ঝালকাঠি'), ('ঝিনাইদহ', 'ঝিনাইদহ'), ('টাঙ্গাইল', 'টাঙ্গাইল'), ('ঠাকুরগাঁও', 'ঠাকুরগাঁও'), ('দিনাজপুর', 'দিনাজপুর'), ('ঢাকা', 'ঢাকা'), ('নওগাঁ', 'নওগাঁ'), ('নাটোর', 'নাটোর'), ('নরসিংদী', 'নরসিংদী'), ('নারায়ণগঞ্জ', 'নারায়ণগঞ্জ'), ('নীলফামারী', 'নীলফামারী'), ('নড়াইল', 'নড়াইল'), ('পাবনা', 'পাবনা'), ('পটুয়াখালী', 'পটুয়াখালী'), ('পিরোজপুর', 'পিরোজপুর'), ('পঞ্চগড়', 'পঞ্চগড়'), ('ফেনী', 'ফেনী'), ('ফরিদপুর', 'ফরিদপুর'), ('বাগেরহাট', 'বাগেরহাট'), ('বরগুনা', 'বরগুনা'), ('বরিশাল', 'বরিশাল'), ('বগুড়া', 'বগুড়া'), ('বান্দরবান', 'বান্দরবান'), ('ব্রাহ্মণবাড়িয়া', 'ব্রাহ্মণবাড়িয়া'), ('ভোলা', 'ভোলা'), ('মাগুরা', 'মাগুরা'), ('মাদারীপুর', 'মাদারীপুর'), ('মানিকগঞ্জ', 'মানিকগঞ্জ'), ('ময়মনসিংহ', 'ময়মনসিংহ'), ('মৌলভীবাজার', 'মৌলভীবাজার'), ('মেহেরপুর', 'মেহেরপুর'), ('মুন্সিগঞ্জ', 'মুন্সিগঞ্জ'), ('যশোর', 'যশোর'), ('জয়পুরহাট', 'জয়পুরহাট'), ('জামালপুর', 'জামালপুর'), ('রাজবাড়ী', 'রাজবাড়ী'), ('রাজশাহী', 'রাজশাহী'), ('রাঙামাটি', 'রাঙামাটি'), ('লালমনিরহাট', 'লালমনিরহাট'), ('লক্ষ্মীপুর', 'লক্ষ্মীপুর'), ('শেরপুর', 'শেরপুর'), ('শরীয়তপুর', 'শরীয়তপুর'), ('সুনামগঞ্জ', 'সুনামগঞ্জ'), ('সিরাজগঞ্জ', 'সিরাজগঞ্জ'), ('সিলেট', 'সিলেট'), ('হবিগঞ্জ', 'হবিগঞ্জ')], max_length=100, null=True, verbose_name='District')),
                ('how_many_copies', models.IntegerField(help_text='Number of copies', verbose_name='How many copies will you take?')),
                ('delivery_medium', models.CharField(choices=[('পোস্ট', 'পোস্ট'), ('কুরিয়ার', 'কুরিয়ার')], help_text='Post or Courier', max_length=20, verbose_name='Through which medium will you take?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Al Itisam Registration',
                'verbose_name_plural': 'Al Itisam Registrations',
                'ordering': ['-created_at'],
            },
        ),
    ]
