# Generated by Django 5.2.8 on 2025-12-18 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0006_khutbaregistration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AlItisamRegistration',
        ),
        migrations.DeleteModel(
            name='KhutbaRegistration',
        ),
        migrations.DeleteModel(
            name='MosqueCourseRegistration',
        ),
        migrations.DeleteModel(
            name='ProgramRegistration',
        ),
        migrations.DeleteModel(
            name='QuranAndDeenCourse',
        ),
    ]
