# Generated by Django 5.2.8 on 2026-02-22 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prints', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='print',
            name='file_url',
        ),
        migrations.AddField(
            model_name='print',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='prints/'),
        ),
    ]
