# Generated by Django 5.2.8 on 2026-02-22 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prints', '0002_remove_print_file_url_print_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printorder',
            name='status',
        ),
    ]
