# Generated by Django 5.2.8 on 2026-02-25 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prints', '0003_remove_printorder_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='print',
            name='file',
        ),
        migrations.AddField(
            model_name='print',
            name='file_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='printorder',
            name='status',
            field=models.CharField(choices=[('RECEIVED', 'Received'), ('PRINTED', 'Printed'), ('SENT', 'Sent')], default='RECEIVED', max_length=20),
        ),
    ]
