# Generated by Django 5.2.8 on 2026-02-27 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prints', '0005_alter_printorder_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='printorder',
            name='anon_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
