# Generated by Django 5.2.8 on 2026-02-27 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prints', '0006_printorder_anon_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='print',
            name='page_range',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='print',
            name='pages_per_slide',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (4, '4'), (8, '8'), (16, '16')], default=1),
        ),
        migrations.AddField(
            model_name='print',
            name='print_color',
            field=models.CharField(choices=[('B_W', 'B&W'), ('COLOR', 'Color')], default='B_W', max_length=10),
        ),
        migrations.AddField(
            model_name='print',
            name='print_pages',
            field=models.CharField(choices=[('ALL', 'All'), ('CUSTOM', 'Custom')], default='ALL', max_length=10),
        ),
        migrations.AddField(
            model_name='print',
            name='sides',
            field=models.CharField(choices=[('SINGLE_SIDED', 'Single Sided'), ('DOUBLE_SIDED', 'Double Sided')], default='SINGLE_SIDED', max_length=20),
        ),
        migrations.AddField(
            model_name='print',
            name='total_pages',
            field=models.IntegerField(default=0),
        ),
    ]
