# Generated by Django 5.2.8 on 2026-02-20 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrintingPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Varsity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('printing_point', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='printer', to='varsity.printingpoint')),
            ],
        ),
        migrations.AddField(
            model_name='printingpoint',
            name='varsity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='printing_points', to='varsity.varsity'),
        ),
    ]
