# Generated by Django 5.2.8 on 2026-01-22 04:19

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FundAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Account name (e.g., 'Dhaka Branch')", max_length=255, unique=True)),
                ('code', models.CharField(help_text="Short code for the account (e.g., 'DHAKA-001')", max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='Account description', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this account is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_fund_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fund Account',
                'verbose_name_plural': 'Fund Accounts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit'), ('credit', 'Credit')], help_text='Deposit (money in) or Credit (money out)', max_length=20)),
                ('category', models.CharField(choices=[('donation', 'Donation'), ('charity', 'Charity'), ('salary', 'Salary'), ('expense', 'Expense'), ('income', 'Income'), ('other', 'Other')], default='other', help_text='Transaction category', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Transaction amount (must be positive)', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('description', models.TextField(help_text='Description of the transaction')),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_index=True, default='pending', help_text='Approval status', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection (if rejected)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(help_text='Fund account this transaction belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='funds.fundaccount')),
                ('approved_by', models.ForeignKey(blank=True, help_text='Super admin who approved/rejected this transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_transactions', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(help_text='User who created this transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='fundaccount',
            index=models.Index(fields=['code'], name='funds_funda_code_931857_idx'),
        ),
        migrations.AddIndex(
            model_name='fundaccount',
            index=models.Index(fields=['is_active'], name='funds_funda_is_acti_d01ef3_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['account', 'status'], name='funds_trans_account_62830e_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status', 'created_at'], name='funds_trans_status_93a3ae_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['category', 'status'], name='funds_trans_categor_0d54c5_idx'),
        ),
    ]
