# Generated by Django 5.2.8 on 2026-01-28 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_courseoffering_courseinstructor_courseenrollment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('topic', models.CharField(blank=True, max_length=255, null=True)),
                ('class_type', models.CharField(choices=[('lecture', 'Lecture'), ('tutorial', 'Tutorial'), ('qa', 'Q&A')], default='lecture', max_length=50)),
                ('recording_url', models.URLField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('course_offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_sessions', to='academics.courseoffering')),
            ],
            options={
                'db_table': 'class_sessions',
                'ordering': ['-session_date'],
                'unique_together': {('course_offering', 'session_date')},
            },
        ),
        migrations.CreateModel(
            name='ClassRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('class_type', models.CharField(choices=[('lecture', 'Lecture'), ('tutorial', 'Tutorial'), ('qa', 'Q&A')], default='lecture', max_length=50)),
                ('location', models.CharField(blank=True, max_length=150, null=True)),
                ('zoom_link', models.URLField(blank=True, null=True)),
                ('youtube_link', models.URLField(blank=True, null=True)),
                ('course_offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_routines', to='academics.courseoffering')),
            ],
            options={
                'db_table': 'class_routines',
                'ordering': ['weekday', 'start_time'],
                'unique_together': {('course_offering', 'weekday', 'start_time')},
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused')], max_length=20)),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL)),
                ('class_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='academics.classsession')),
            ],
            options={
                'db_table': 'attendance',
                'ordering': ['student__full_name'],
                'unique_together': {('class_session', 'student')},
            },
        ),
    ]
